# Generated by Django 6.1.1 on 2026-10-08 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=32, unique=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('file_sha', models.CharField(blank=True, max_length=64)),
                ('poc_count', models.PositiveIntegerField(default=0)),
                ('top_repo_url', models.URLField(blank=True, max_length=512)),
                ('top_stars', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CVE',
                'verbose_name_plural': 'CVEs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CVEExploit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_full_name', models.CharField(max_length=255)),
                ('repo_url', models.URLField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('stars', models.IntegerField(default=0)),
                ('is_fork', models.BooleanField(default=False)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploits', to='cve_monitor.cve')),
            ],
            options={
                'ordering': ('-stars',),
                'unique_together': {('cve', 'repo_full_name')},
            },
        ),
    ]
