# Generated by Django 6.1.1 on 2026-10-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='discovered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
