# Generated by Django 6.1.1 on 2026-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_monitor', '0002_cve_discovered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='cvss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='cwe',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='cve',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='enrich_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cve',
            name='enriched_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='severity',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
