# Generated by Django 6.1.1 on 2026-10-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to auto-generate from the title.', max_length=240, unique=True)),
                ('author', models.CharField(default='RadvanSec', max_length=120)),
                ('summary', models.CharField(help_text='One or two sentences shown on the blog list and homepage.', max_length=300)),
                ('read_minutes', models.PositiveSmallIntegerField(default=5)),
                ('body_html', models.TextField(help_text='Full post content as HTML (h2, p, pre/code, ul/li, div.callout, etc.). Only paste content you trust, it is rendered unescaped.')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
