# Generated by Django 6.1.1 on 2026-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(blank=True, help_text='Optional poster image shown at the top of the post.', null=True, upload_to='posters/%Y/%m/'),
        ),
    ]
